// (c) 2026
// Licensed under LGPLv3 - http://www.gnu.org/licenses/lgpl-3.0.txt

package de.mossgrabers.pull.core.api;

import java.util.Objects;


/**
 * User-selected routing for pressure generated by the Push pad grid.
 *
 * @param mode Pressure output mode
 * @param controller MIDI controller number when the mode is {@link Mode#CONTROL_CHANGE}
 */
public record GridPressureConfiguration (Mode mode, int controller)
{
    /** Disabled pressure routing. */
    public static final GridPressureConfiguration OFF = new GridPressureConfiguration (Mode.OFF, 0);

    /** Per-note poly-aftertouch routing. */
    public static final GridPressureConfiguration POLY = new GridPressureConfiguration (Mode.POLY_AFTERTOUCH, 0);

    /** Aggregate channel-aftertouch routing. */
    public static final GridPressureConfiguration CHANNEL = new GridPressureConfiguration (Mode.CHANNEL_AFTERTOUCH, 0);


    /**
     * Validate one routing configuration.
     */
    public GridPressureConfiguration
    {
        mode = Objects.requireNonNull (mode, "mode");
        if (controller < 0 || controller > 127)
            throw new IllegalArgumentException ("controller must be between 0 and 127");
        if (mode != Mode.CONTROL_CHANGE && controller != 0)
            throw new IllegalArgumentException ("controller is used only for control-change pressure");
    }


    /**
     * Route pressure to one MIDI control-change number.
     *
     * @param controller MIDI controller number
     * @return Control-change pressure routing
     */
    public static GridPressureConfiguration controlChange (final int controller)
    {
        return new GridPressureConfiguration (Mode.CONTROL_CHANGE, controller);
    }


    /** Pressure output modes. */
    public enum Mode
    {
        /** Ignore pressure. */
        OFF,
        /** Send pressure for the mapped note. */
        POLY_AFTERTOUCH,
        /** Send aggregate channel pressure. */
        CHANNEL_AFTERTOUCH,
        /** Send pressure through one MIDI controller. */
        CONTROL_CHANGE
    }
}
