#!/usr/bin/env python3
"""Validate Push 2 palette JSON and generate the Java runtime data holder."""

import argparse
import hashlib
import json
import os
import re
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PROFILES = ROOT / "resources/push2-palettes/profiles"
ACTIVE = ROOT / "resources/push2-palettes/active.txt"
OUTPUT = (
    ROOT
    / "pull-shell/src/main/java/de/mossgrabers/controller/ableton/push/controller"
    / "PushPaletteData.java"
)
RGB = re.compile(r"#[0-9A-F]{6}")


class PaletteError(Exception):
    """A palette source or generated file violated an invariant."""


def read_profile(path):
    try:
        profile = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise PaletteError(f"{path}: {error}") from error

    required = ("schemaVersion", "id", "label", "status", "summary", "colorModel")
    if profile.get("schemaVersion") != 1 or any(key not in profile for key in required):
        raise PaletteError(f"{path}: missing profile metadata")
    if path.stem != profile["id"]:
        raise PaletteError(f"{path}: id must match filename")

    entries = profile.get("entries")
    if not isinstance(entries, list) or len(entries) != 128:
        raise PaletteError(f"{path}: expected exactly 128 entries")

    logical = []
    programmed = []
    paired = None
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict) or entry.get("index") != index:
            raise PaletteError(f"{path}: entry {index} has the wrong index")
        target = entry.get("targetRgb")
        if not isinstance(target, str) or RGB.fullmatch(target) is None:
            raise PaletteError(f"{path}: entry {index} has invalid targetRgb")
        has_programmed = "programmedRgb" in entry
        if paired is None:
            paired = has_programmed
        if paired != has_programmed:
            raise PaletteError(f"{path}: programmedRgb must be present on all or no entries")
        value = entry.get("programmedRgb", target)
        if not isinstance(value, str) or RGB.fullmatch(value) is None:
            raise PaletteError(f"{path}: entry {index} has invalid programmedRgb")
        logical.append(target)
        programmed.append(value)

    return profile, logical, programmed if paired else None


def load_profiles():
    profiles = {}
    for path in sorted(PROFILES.glob("*.json")):
        profile, logical, programmed = read_profile(path)
        profile_id = profile["id"]
        if profile_id in profiles:
            raise PaletteError(f"duplicate profile id {profile_id}")
        profiles[profile_id] = (path, profile, logical, programmed)
    if not profiles:
        raise PaletteError(f"{PROFILES}: no profiles found")
    return profiles


def active_id():
    try:
        value = ACTIVE.read_text(encoding="utf-8")
    except OSError as error:
        raise PaletteError(f"{ACTIVE}: {error}") from error
    profile_id = value.strip()
    if value != profile_id + "\n":
        raise PaletteError(f"{ACTIVE}: expected one profile id and newline")
    return profile_id


def color_rows(colors):
    rows = []
    for start in range(0, 128, 4):
        values = [
            "{ 0x%s, 0x%s, 0x%s }" % (color[1:3], color[3:5], color[5:7])
            for color in colors[start : start + 4]
        ]
        rows.append("        " + ", ".join(values) + ",")
    rows[-1] = rows[-1].removesuffix(",")
    return "\n".join(rows)


def render_java(profile_id, path, logical, programmed):
    source_hash = hashlib.sha256(path.read_bytes()).hexdigest()
    programmed_source = "    static final boolean HAS_PROGRAMMED_COLORS = false;\n    static final int [] [] PROGRAMMED_COLORS = COLORS;"
    if programmed is not None:
        programmed_source = f"""    static final boolean HAS_PROGRAMMED_COLORS = true;

    // @formatter:off
    static final int [] [] PROGRAMMED_COLORS =
    {{
{color_rows(programmed)}
    }};
    // @formatter:on"""

    return f"""// Generated by tools/push2-palette/generate.py. Do not edit by hand.
// Source profile: resources/push2-palettes/profiles/{profile_id}.json

package de.mossgrabers.controller.ableton.push.controller;


/** Selected logical Push 2 palette and its final hardware drive values. */
final class PushPaletteData
{{
    static final String PROFILE_ID    = "{profile_id}";
    static final String SOURCE_SHA256 = "{source_hash}";

    // @formatter:off
    static final int [] [] COLORS =
    {{
{color_rows(logical)}
    }};
    // @formatter:on

{programmed_source}


    private PushPaletteData ()
    {{
        // Generated data holder
    }}
}}
"""


def replace_text(path, content):
    descriptor, temporary = tempfile.mkstemp(dir=path.parent, prefix=path.name + ".")
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
        Path(temporary).replace(path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def selected(profiles, requested=None):
    profile_id = requested or active_id()
    if profile_id not in profiles:
        raise PaletteError(f"unknown profile {profile_id}")
    return profile_id, profiles[profile_id]


def duplicate_count(colors):
    return len(colors) - len(set(colors))


def main():
    parser = argparse.ArgumentParser()
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--list", action="store_true")
    action.add_argument("--status", action="store_true")
    action.add_argument("--check", action="store_true")
    action.add_argument("--use", metavar="ID")
    args = parser.parse_args()

    try:
        profiles = load_profiles()
        if args.list:
            current = active_id()
            for profile_id, (_, profile, _, _) in profiles.items():
                print(f"{'*' if profile_id == current else ' '} {profile_id:24s} {profile['label']}")
            return

        profile_id, (path, profile, logical, programmed) = selected(profiles, args.use)
        java = render_java(profile_id, path, logical, programmed)
        if args.use:
            replace_text(OUTPUT, java)
            replace_text(ACTIVE, profile_id + "\n")
            print(f"Selected {profile_id}: 128 colors")
            return
        if args.check:
            if OUTPUT.read_text(encoding="utf-8") != java:
                raise PaletteError(f"{OUTPUT}: generated data is stale")
            print(f"OK: {len(profiles)} profiles; active={profile_id}; colors=128")
            return
        print(f"{profile_id}: {profile['label']}\n{profile['summary']}\nduplicates={duplicate_count(logical)}")
    except (OSError, PaletteError) as error:
        parser.exit(1, f"push2-palette: {error}\n")


if __name__ == "__main__":
    main()
